<?php

/**
 * Implements hook_schema().
 */
function ebms_core_schema(): array {
  return [
    'on_demand_config' => [
      'description' => 'Configuration values which we only want loaded when they are explicitly requested, and which we do not want to be controlled by the Drupal cache system.',
      'fields' => [
        'name' => [
          'description' => 'Unique name of the configuration (for example, article-type-ancestors).',
          'type' => 'varchar',
          'length' => 255,
          'not null' => TRUE,
        ],
        'value' => [
          'description' => 'JSON-encoded value for the configuration.',
          'type' => 'text',
          'size' => 'normal',
        ],
      ],
      'primary key' => ['name'],
    ],
  ];
}

/**
 * Migrate legacy authmap entries to externalauth_authmap.
 */
function ebms_core_update_9001() {
  $authmap_service = \Drupal::service('externalauth.authmap');
  $db = \Drupal::database();

  if ($db->schema()->tableExists('authmap')) {
    // Pull from the old legacy table
    $results = $db->query("SELECT uid, authname FROM {authmap}")->fetchAll();
    $count = 0;

    foreach ($results as $row) {
      $account = \Drupal\user\Entity\User::load($row->uid);

      // The .get() method returns the authname if it exists, otherwise FALSE
      if ($account && !$authmap_service->get($row->uid, 'samlauth')) {
        $authmap_service->save($account, 'samlauth', $row->authname);
        $count++;
      }
    }

    \Drupal::messenger()->addMessage("Successfully migrated $count new users to the SAML authmap.");
  }
}
